#!/usr/bin/env bash
# Bash script that installs Nginx server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
service nginx start
echo "Hello World" > /var/www/html/index.nginx-debian.html
