#!/usr/bin/env bash
# Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get -y install nginx
service nginx start
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
