#!/usr/bin/env bash
# Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update -y
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4" /etc/nginx/sites-available/default
service nginx start
