#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
# Add a custom Nginx response header
sudo apt-get update -y
sudo apt-get install nginx -y

sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i "/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "/server_name _;/ a error_page 404 /404.html;" /etc/nginx/sites-available/default

sudo sed -i "/server_name _;/ a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

sudo service nginx restart
