#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
sudo apt-get update
sudo apt-get install haproxy -y
sudo echo "ENABLED=1" > /etc/default/haproxy
# shellcheck issue fixed
sed -i "/504.http/a frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend My_Web_Servers\n\nbackend My_Web_Servers\n\tbalance roundrobin\n\tserver 3872-web-01 54.90.197.149:80 check\n\tserver 3872-web-02 54.166.41.209:80 check" /etc/haproxy/haproxy.cfg
service haproxy restart
