#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get update
sudo apt-get install haproxy -y
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# tee - read from standard input and write to standard output and files
sudo echo "
frontend thefrontend
        bind 0.0.0.0:80
        default_backend myservers
        
backend myservers
        balance roundrobin
        server 3872-web-01 54.90.197.149 check
        server 3872-web-02 54.166.41.209 check" | sudo tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
