#!/usr/bin/env bash
#This script prints 10 times the string in echo using while
while ((i < 10));
do
    if [[ "$i" == 3 ]];
    then
        echo "bad luck"
    elif [[ "$i" == 7 ]];
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
