#!/usr/bin/env bash
#The content of the current directory in a list format Where only the part of the name after the first dash is displayed
ls="$(ls)"
for i in $ls;
do
	echo "$i" | cut -d'-' -f2
done
